swagger: '2.0'
info:
  title: Grassroots Football Management API
  description: API Gateway for Grassroots Football Management microservices
  version: 1.0.0
host: gfm-1ykrsotxghm8m.apigateway.grassroots-football-management.cloud.goog
x-google-endpoints:
- name: gfm-1ykrsotxghm8m.apigateway.grassroots-football-management.cloud.goog
  allowCors: True
schemes:
  - https
paths:
  # Authentication Microservice Routes
  /signup:
    post:
      x-google-backend:
        address: https://microservice-authentication-180320540339.europe-west2.run.app/signup  
      summary: Register a new user
      description: Register a new user with email, password, and name
      operationId: registerUser
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: User registration data
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string
              name:
                type: string
              role:
                type: string
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Invalid input or email already exists
        '500':
          description: Internal server error

  /signin:
    post:
      x-google-backend:
        address: https://microservice-authentication-180320540339.europe-west2.run.app/signin  
      summary: Sign in a user
      description: Authenticate a user with an ID token
      operationId: signInUser
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: User sign-in data
          required: true
          schema:
            type: object
            properties:
              idToken:
                type: string
      responses:
        '200':
          description: User signed in successfully
        '400':
          description: Invalid input
        '401':
          description: Invalid or expired ID token
        '500':
          description: Internal server error

  /logout:
    post:
      x-google-backend:
        address: https://microservice-authentication-180320540339.europe-west2.run.app/logout 
      summary: Log out a user
      description: Revoke a user's refresh tokens
      operationId: logoutUser
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: User logout data
          required: true
          schema:
            type: object
            properties:
              idToken:
                type: string
      responses:
        '200':
          description: User logged out successfully
        '400':
          description: Invalid input
        '401':
          description: Invalid or expired ID token
        '500':
          description: Internal server error

  # User Management Microservice Routes
  /user/create:
    post:
      x-google-backend:
        address: https://microservice-user-management-180320540339.europe-west2.run.app/user/create
      summary: Create a new user in Firestore
      description: Create a new user document in Firestore with email, name, and role
      operationId: createUser
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: User creation data
          required: true
          schema:
            type: object
            properties:
              uid:
                type: string
              email:
                type: string
              name:
                type: string
              role:
                type: string
      responses:
        '201':
          description: User created successfully
        '400':
          description: Invalid input or user already exists
        '500':
          description: Internal server error
  /user/update:
    post:
      x-google-backend:
        address: https://microservice-user-management-180320540339.europe-west2.run.app/user/update  
      summary: Update a user's profile
      description: Update a user's profile in Firestore
      operationId: updateUserProfile
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: User profile data to update
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
              name:
                type: string
      responses:
        '200':
          description: User profile updated successfully
        '400':
          description: Invalid input
        '500':
          description: Internal server error

  /user/check:
    get:
      x-google-backend:
        address: https://microservice-user-management-180320540339.europe-west2.run.app/user/check  
      summary: Check if a user exists
      description: Check if a user exists in Firestore by email
      operationId: checkUserExists
      produces:
        - application/json
      parameters:
        - in: query
          name: email
          description: The email of the user to check
          required: true
          type: string
      responses:
        '200':
          description: Successful response indicating whether the user exists
          schema:
            type: object
            properties:
              exists:
                type: boolean
              message:
                type: string
        '400':
          description: Missing or invalid email parameter
        '500':
          description: Internal server error

  # Team Management Microservice Routes
  /club/create-join:
    post:
      x-google-backend:
        address: https://microservice-team-management-180320540339.europe-west2.run.app/club/create-join
      summary: Create or join a club
      operationId: createOrJoinClub
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              clubName:
                type: string
              coachEmail:
                type: string
              ageGroups:
                type: array
                items:
                  type: string
              divisions:
                type: array
                items:
                  type: string
              county:
                type: string
      responses:
        '201':
          description: New club created
        '200':
          description: Coach added to existing club
        '400':
          description: Invalid input
        '500':
          description: Internal server error

  /club/search:
    get:
      x-google-backend:
        address: https://microservice-team-management-180320540339.europe-west2.run.app/club/search
      summary: Search for clubs
      operationId: searchClubs
      produces:
        - application/json
      parameters:
        - in: query
          name: clubName
          type: string
          description: Club name to search
          required: false
        - in: query
          name: county
          type: string
          description: County to filter by
          required: false
        - in: query
          name: ageGroup
          type: string
          description: Age group to filter by
          required: false
        - in: query
          name: division
          type: string
          description: Division to filter by
          required: false
      responses:
        '200':
          description: List of clubs
        '500':
          description: Internal server error

  /club/join-request:
    post:
      x-google-backend:
        address: https://microservice-team-management-180320540339.europe-west2.run.app/club/join-request
      summary: Submit a join request
      operationId: submitJoinRequest
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              playerEmail:
                type: string
              clubName:
                type: string
      responses:
        '201':
          description: Join request submitted
        '400':
          description: Invalid input
        '500':
          description: Internal server error